backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "contributor"
    label: "Contributor"
    folder: "content/markdown/contributors"
    identifier_field: lastName
    create: true
    editor:
     preview: false
    fields:
      - { label: "Tag Type", name: "tagType", widget: "hidden", default: "contributor" }
      - { label: "First Name", name: "firstName", widget: "string" }
      - { label: "Last Name", name: "lastName", widget: "string" }
      - { label: "Role", name: "role", widget: "string" }
      - { label: "Headshot", name: "headshot", widget: "image"}
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "venue"
    label: "Venue"
    folder: "content/markdown/venues"
    identifier_field: name
    create: true
    editor:
     preview: false
    fields:
      - { label: "Tag Type", name: "tagType", widget: "hidden", default: "venue" }
      - { label: "Event Title", name: "eventTitle", widget: "string" }
      - { label: "Event Date", name: "eventDate", widget: "date" }
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Logo", name: "logo", widget: "image"}
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "blog"
    label: "Blog"
    folder: "content/markdown/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
     preview: false
    fields:
      - { label: "Tag Type", name: "tagType", widget: "hidden", default: "blogPost" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Resource Files", 
          name: "resourceFiles", 
          widget: "list", 
          fields: [
            { label: Name, name: name, required: true, widget: string },
            { label: File, name: file, required: true, widget: file},
          ]}
  - name: "eventSchedule"
    label: "Event Schedule"
    folder: "content/markdown/eventSchedule"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
     preview: false
    fields:
      - { label: "Tag Type", name: "tagType", widget: "hidden", default: "eventSchedule" }
      - { label: "Event Title", name: "eventTitle", widget: "string" }
      - { label: "Days", 
          name: "days", 
          widget: "list", 
          fields: [
            { label: Day of the Week, name: dayWeek, required: true, widget: string },
            { label: Date, name: date, required: true, widget: "date"},
            { label: Schedule Item, 
              name: scheduleItem,
              widget: list,
              fields: [
                { label: Item Name, name: itemName, required: true, widget: string },
                { label: Start Time, name: startTime, required: true, widget: datetime },
                { label: End Time, name: endTime, required: true, widget: datetime },
                { label: Description, name: itemDescription, required: true, widget: string },
              ]
              }
          ]}
