backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "contributor"
    label: "Contributor"
    folder: "content/markdown/contributors"
    description: "Add even contributors (speakers, moderators, workshop facilitators. Add name, role, headshot image, and bio blurb. On page, they are arranged alphabetially by last name."
    identifier_field: lastName
    create: true
    editor:
     preview: false
    fields:
      - { label: "Tag Type", name: "tagType", widget: "hidden", default: "contributor" }
      - { label: "First Name", name: "firstName", widget: "string" }
      - { label: "Last Name", name: "lastName", widget: "string" }
      - { label: "Role", name: "role", widget: "string" }
      - { label: "Headshot", name: "headshot", widget: "image"}
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "venue"
    label: "Venue"
    folder: "content/markdown/venues"
    description: "Add venue information. Add associated event details (name, date), venue name and logo."
    identifier_field: name
    create: true
    editor:
     preview: false
    fields:
      - { label: "Tag Type", name: "tagType", widget: "hidden", default: "venue" }
      - { label: "Event Title", name: "eventTitle", widget: "string" }
      - { label: "Event Date", name: "eventDate", widget: "date" }
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Logo", name: "logo", widget: "image"}
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "blog"
    label: "Blog"
    folder: "content/markdown/blog"
    description: "Blog post with fields for linking file resources."
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
     preview: false
    fields:
      - { label: "Tag Type", name: "tagType", widget: "hidden", default: "blogPost" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Resource Files", 
          name: "resourceFiles", 
          widget: "list", 
          fields: [
            { label: Name, name: name, required: true, widget: string },
            { label: File, name: file, required: true, widget: file},
          ]}
  - name: "eventSchedule"
    label: "Event Schedule"
    folder: "content/markdown/eventSchedule"
    description: "Add schedule for events. For each schedule, add days and then schedule items including name, location, start/end times, and description. Most current event schdule will be displayed on /schedule page."
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    identifier_field: eventTitle
    editor:
     preview: false
    fields:
      - { label: "Tag Type", name: "tagType", widget: "hidden", default: "eventSchedule" }
      - { label: "Event Title", name: "eventTitle", widget: "string" }
      - { label: "Event Start Date", name: "eventStartDate", widget: "date" }
      - { label: "Days", 
          name: "days", 
          widget: "list", 
          fields: [
            { label: Day of the Week, name: dayWeek, required: true, widget: string },
            { label: Date, name: date, required: true, widget: "date"},
            { label: Schedule Items, 
              name: scheduleItems,
              widget: list,
              fields: [
                { label: Item Name, name: itemName, required: true, widget: string },
                { label: Location, name: location, widget: string },
                { label: Start Time, name: startTime, required: true, widget: datetime, default: "", format: "LLL"},
                { label: End Time, name: endTime, required: false, widget: datetime, default: "", format: "LLL" },
                { label: Speakers, name: speakers, required: false, widget: string },
                { label: Moderator, name: moderator, required: false, widget: string },
                { label: Description, name: itemDescription, widget: "markdown"},
              ]
              }
          ]}
