backend:
  name: git-gateway
  branch: master
  open_authoring: true

media_folder: static/img
public_folder: /img
publish_mode: editorial_workflow

collections:
  - name: "Contributor"
    label: "Contributor"
    folder: "content/markdown/contributors"
    description: "Add details for speakers, moderators, workshop faciliators etc."
    create: true
    editor:
     preview: false
    fields:
      - { label: "Type Tag", name: "typeTag", widget: "hidden", default: "speaker" }
      - { label: "First Name", name: "firstName", widget: "string" }
      - { label: "Last Name", name: "lastName", widget: "string" }
      - { label: "Role", name: "role", widget: "string" }
      - { label: "Bio", name: "bio", widget: "markdown" }
  